name: "CI"
on: "push"

jobs:
  Verify-Cache:
    name: "Verify Cache"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache --check-cache"

  Lint:
    runs-on: "ubuntu-latest"
    needs: [Verify-Cache]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache"

      - name: "Lint Code"
        run: "yarn ci-lint"

  Build:
    runs-on: "ubuntu-latest"
    needs: [Verify-Cache]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache"

      - name: "Compile Code"
        run: "yarn build"

  Test:
    strategy: { matrix: { node: [12, 14, 16, 17, 18] } }
    name: "Test (Node ${{ matrix.node }})"
    runs-on: ubuntu-latest
    needs: [Lint, Build]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "${{ matrix.node }}" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache"

      - name: "Test Code"
        run: "yarn test"

  Publish:
    runs-on: "ubuntu-latest"
    needs: [Lint, Build, Test]
    concurrency: "npm"
    if: "false"

    environment:
      name: "NPM"
      url: "https://www.npmjs.com/package/httpcord"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Install Dependencies"
        run: "yarn --immutable --immutable-cache"

      - name: "Compile Code"
        run: "yarn build"

      - name: "Bump Version"
        run: npm version prerelease --preid=dev --no-git-tag-version

        # These files do not affect installation and only bloat package size.
      - name: "Cleanup Unnecessary Files"
        run: |
          rm -rf src .yarn
          rm .pnp.cjs .pnp.loader.mjs

      - name: "Publish to NPM"
        env: { NPM_TOKEN: "${{ secrets.NPM_TOKEN }}" }
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm deprecate httpcord@"~$(jq --raw-output '.version' package.json)" "This old development version is no longer supported." || true
          npm publish --tag dev
