name: "CI"
on: "push"

jobs:
  Lint:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache --check-cache"

      - name: "Lint Code"
        run: "yarn lint"

  Build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache --check-cache"

      - name: "Compile Code"
        run: "yarn build --noEmit"

  Test:
    runs-on: ubuntu-latest
    needs: [Lint, Build]
    strategy: { matrix: { node: [12, 14, 16, 17] } }

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "${{ matrix.node }}" }

      - name: "Check & Install Dependencies"
        run: "yarn --immutable --immutable-cache"

      - name: "Test Code"
        run: "yarn test"

  Publish:
    runs-on: "ubuntu-latest"
    needs: [Lint, Build, Test]
    concurrency: "npm"

    environment:
      name: "NPM"
      url: "https://www.npmjs.com/package/httpcord"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Install Dependencies"
        run: "yarn --immutable --immutable-cache"

      - name: "Compile Code"
        run: "yarn build"

      - name: "Bump Version"
        run: "node .github/workflows/bump.js ${{ github.sha }}"

      - name: "Publish to NPM"
        env: { NPM_TOKEN: "${{ secrets.NPM_TOKEN }}" }
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish
